name: Deploy via FTP

on:
  workflow_run:
    workflows: ["Build and Upload Artifact"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download the artifact uploaded in the Build workflow
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: School-Website  # Matches the artifact name from the previous workflow
          path: ./  # Download to the current working directory

      # Step 3: Sync files to FTP
      - name: Sync files to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: linux22.dandomain.dk
          username: ${{ secrets.FTPUSERNAME }}
          password: ${{ secrets.FTPPASSWORD }}
          protocol: ftps
          server-dir: www  # Replace with your target directory on the server
          local-dir: ./dist  # Path to the artifact content after extraction (adjust if necessary)
